In [41]:
from sklearn import datasets

n = 5
x_train = [0]*n
x_test =[0]*n
y_train = [0]*n
y_test = [0]*n

for i in range(0,n):
    data = datasets.make_friedman1(n_samples = 100, n_features = 5, noise = 1)
    x_train[i] = data[0][0:50]
    x_test[i] = data[0][50:data[0].shape[0]]
    y_train[i] = data[1][0:50]
    y_test[i] = data[1][50:data[1].shape[0]]
    
for i in range(0,n):
    print(y_test[i])
    print(len(y_test[i]))
    print('------------------------')

[16.02919828 17.1620625  10.11812795  8.8241567  14.56742493 13.3196932
  7.2067826  12.80422007  9.80360341 11.35180301 15.29962898 14.89863051
 14.07077429  8.07992481 10.89866657 22.62183973 13.56445245 10.61366205
 16.28002275 14.99920851 12.16059808 23.30445803  4.73891906 17.53664288
  9.30212103 18.95649939  9.09824937 10.8417204  14.41681922 19.98583984
 17.22931835  7.29646081 18.06574839 19.11259503 13.79589946  9.12004858
 17.18886426 12.097857   20.26420409  9.05734349 16.51631627 11.70526266
  9.90128521 16.71186694 13.84690399 12.17631507 12.77993572 16.21019362
 19.68901071 10.03687748]
50
------------------------
[ 2.20409597 10.54759924 15.07711186 23.15493111 19.20642307 14.62982341
 13.23382294 14.42403096  9.85550251  6.69795746  9.45715515  2.00441555
 17.53463225 11.34739227 10.7768305  18.46172559 19.60851774 10.70407687
  9.33192847 10.63219402  9.3197161  18.1850446  16.8273288  18.93869494
 19.60877257 15.96357884  3.7392021  13.21201604 14.7055305  12.4241705

In [23]:
#compare grid and random search. search over all combinations. random forest

'''
note that, for random forest:
n_estimators = num.trees
min_samples_leaf = min.node.size
max_features = mtry
max_samples = sample.fraction
'''

import math
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.ensemble import RandomForestRegressor
from sklearn import model_selection
from sklearn.metrics import mean_squared_error
import time

par_grid = {'n_estimators':[1,2,3,4,5], 
        'min_samples_leaf':np.linspace(0.1,0.5,5), 
        'max_features':np.linspace(0.1,0.5,5), 
        'max_samples':np.linspace(0.1,0.5,5)}

results_rs = pd.DataFrame(np.zeros((n,4)), columns = ['out-score', 'in-score', 'time', 'params'])
results_gs = pd.DataFrame(np.zeros((n,4)), columns = ['out-score', 'in-score', 'time', 'params'])

for i in range(0,n):
    gs = model_selection.GridSearchCV(estimator = RandomForestRegressor(), 
                                      param_grid = par_grid, 
                                      scoring = 'neg_root_mean_squared_error', 
                                      cv = 3)
    
    start = time.thread_time()
    gs.fit(x_train[i], y_train[i])
    stop = time.thread_time()
    
    results_gs.loc[i, 'params'] = str(gs.best_params_)
    results_gs.loc[i, 'in-score'] = - gs.best_score_
    gs_pred_i = gs.best_estimator_.predict(x_test[i])
    results_gs.loc[i, 'out-score'] = math.sqrt(mean_squared_error(y_true = np.array(y_test[i]), y_pred = gs_pred_i))
    results_gs.loc[i, 'time'] = stop - start

    rs = model_selection.RandomizedSearchCV(estimator = RandomForestRegressor(), 
                                        param_distributions = par_grid,
                                        n_iter = 5**4,
                                        scoring = 'neg_root_mean_squared_error',
                                        cv = 3)
    
    start = time.thread_time()
    rs.fit(x_train[i], y_train[i])
    stop = time.thread_time()
    
    results_rs.loc[i, 'params'] = str(rs.best_params_)
    results_rs.loc[i, 'in-score'] = - rs.best_score_
    rs_pred_i = rs.best_estimator_.predict(x_test[i])
    results_rs.loc[i, 'out-score'] = math.sqrt(mean_squared_error(y_true = np.array(y_test[i]), y_pred = rs_pred_i))
    results_rs.loc[i, 'time'] = stop - start
    
print(results_gs['out-score'].mean())
print(results_rs['out-score'].mean())
results_gs.to_csv('~/Python Projects/results_gs.csv')
results_rs.to_csv('~/Python Projects/results_rs.csv')

3.9391427048497434
4.226721371205324


NameError: name 'results' is not defined

In [27]:
results_gs.to_csv('~/Python Projects/results_gs.csv')
results_rs.to_csv('~/Python Projects/results_rs.csv')

In [38]:
from sklearn import datasets

n = 1
x_train = [0]*n
x_test =[0]*n
y_train = [0]*n
y_test = [0]*n

for i in range(0,n):
    data = datasets.make_friedman1(n_samples = 100, n_features = 5, noise = 1)
    x_train[i] = data[0][0:50]
    x_test[i] = data[0][50:data[0].shape[0]]
    y_train[i] = data[1][0:50]
    y_test[i] = data[1][50:data[1].shape[0]]

print(x_train[0])

[[0.34490019 0.80920184 0.73283839 0.16835489 0.04000853]
 [0.55338422 0.81720885 0.78669861 0.24271171 0.95268214]
 [0.00329862 0.98445742 0.93162536 0.88929733 0.54750683]
 [0.79593389 0.5839527  0.36064601 0.41866356 0.47822459]
 [0.24464988 0.06288128 0.34773693 0.36866512 0.41325036]
 [0.1434114  0.02484072 0.2428424  0.44296095 0.99563947]
 [0.08844925 0.68264018 0.23325306 0.00317862 0.18883279]
 [0.34116934 0.05184034 0.98870941 0.37584013 0.68024464]
 [0.87351935 0.722263   0.42454288 0.08449922 0.09107727]
 [0.21325396 0.80000102 0.28261197 0.88179662 0.47950409]
 [0.5076014  0.64427825 0.86924018 0.98327823 0.04672867]
 [0.97619647 0.81957585 0.16179724 0.27679852 0.78352827]
 [0.8294062  0.91442708 0.699453   0.0437234  0.65975889]
 [0.31316741 0.44364389 0.46340941 0.37122897 0.37124332]
 [0.97461861 0.09893752 0.08474887 0.16932111 0.92700136]
 [0.46300427 0.30159743 0.4637354  0.59987129 0.06754936]
 [0.26978306 0.74308833 0.00615403 0.76266391 0.59847779]
 [0.66670483 0

In [42]:
#compare grid and random search. search over all combinations. xgboost

import math
import pandas as pd
import numpy as np
from sklearn import datasets
from xgboost import XGBRegressor
from sklearn import model_selection
from sklearn.metrics import mean_squared_error
import time

par_grid = {'booster':['gbtree', 'gblinear', 'dart'], 
            'learning_rate':np.linspace(0,1,5),
           'reg_alpha':np.linspace(0,10,5),
           'reg_lambda':np.linspace(0,10,5)}

results_rs = pd.DataFrame(np.zeros((n,4)), columns = ['out-score', 'in-score', 'time', 'params'])
results_gs = pd.DataFrame(np.zeros((n,4)), columns = ['out-score', 'in-score', 'time', 'params'])

for i in range(0,n):
    gs = model_selection.GridSearchCV(estimator = XGBRegressor(), 
                                      param_grid = par_grid, 
                                      scoring = 'neg_root_mean_squared_error', 
                                      cv = 3)
    
    start = time.thread_time()
    gs.fit(x_train[i], y_train[i])
    stop = time.thread_time()
    
    results_gs.loc[i, 'params'] = str(gs.best_params_)
    results_gs.loc[i, 'in-score'] = - gs.best_score_
    gs_pred_i = gs.best_estimator_.predict(x_test[i])
    results_gs.loc[i, 'out-score'] = math.sqrt(mean_squared_error(y_true = np.array(y_test[i]), y_pred = gs_pred_i))
    results_gs.loc[i, 'time'] = stop - start

    rs = model_selection.RandomizedSearchCV(estimator = XGBRegressor(), 
                                        param_distributions = par_grid,
                                        n_iter = 3*5**3,
                                        scoring = 'neg_root_mean_squared_error',
                                        cv = 3)
    
    start = time.thread_time()
    rs.fit(x_train[i], y_train[i])
    stop = time.thread_time()
    
    results_rs.loc[i, 'params'] = str(rs.best_params_)
    results_rs.loc[i, 'in-score'] = - rs.best_score_
    rs_pred_i = rs.best_estimator_.predict(x_test[i])
    results_rs.loc[i, 'out-score'] = math.sqrt(mean_squared_error(y_true = np.array(y_test[i]), y_pred = rs_pred_i))
    results_rs.loc[i, 'time'] = stop - start
    
print(results_gs['out-score'].mean())
print(results_rs['out-score'].mean())
results_gs.to_csv('~\Python Projects\results_gs.csv')
results_rs.to_csv('~\Python Projects\results_rs.csv')

3.3601704096321328
3.35974217401847


PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Neil/Python Projects/results_gs.csv'

In [46]:
#compare grid and random search. search along only 1 parameter at a time. random forest.
import numpy as np
from sklearn import datasets
from sklearn.ensemble import RandomForestRegressor
from sklearn import model_selection
import time

x = datasets.make_friedman1(n_samples = 50, n_features = 5, noise = 0)

#I decided to define the default parameters as somewhere in the middle of the entire space
def_pars = {'n_estimators':3, 'min_samples_leaf':0.3, 'max_samples':0.3, 'max_features':0.3}
best_pars_gs = def_pars
best_pars_rs = def_pars

param_grid = {'n_estimators':[1,2,3,4,5], 
        'min_samples_leaf':np.linspace(0.1,0.5,5), 
        'max_features':np.linspace(0.1,0.5,5), 
        'max_samples':np.linspace(0.1,0.5,5)}
space_sizes = {'n_estimators':5, 'min_samples_leaf':5, 'max_features':5, 'max_samples':5}

for par in param_grid:
    rf = RandomForestRegressor(n_estimators = def_pars['n_estimators'],
                                min_samples_leaf = def_pars['min_samples_leaf'],
                                max_samples = def_pars['max_samples'],
                                max_features = def_pars['max_features']
                               )
    one_par = {par:param_grid[par]}
    gs = model_selection.GridSearchCV(estimator = rf,
                                      param_grid = one_par,
                                      cv = 3,
                                      scoring = 'neg_mean_squared_error'
                                     )
    gs.fit(x[0], x[1])
    best_pars_gs[par] = gs.best_params_[par]
    rs = model_selection.RandomizedSearchCV(estimator = rf,
                                           param_distributions = one_par,
                                           cv = 3,
                                            n_iter = space_sizes[par],
                                           scoring = 'neg_mean_squared_error')
    rs.fit(x[0], x[1])
    best_pars_rs[par] = rs.best_params_[par]

print(best_pars_gs)
print(best_pars_rs)
rf_best = RandomForestRegressor(best_pars_gs['n_estimators'], 
                                min_samples_leaf = best_pars_gs['min_samples_leaf'],
                               max_samples = best_pars_gs['max_samples'],
                               max_features = best_pars_gs['max_features'])
rf_best.fit(x[0], x[1])
print(rf_best.best_score_)

{'n_estimators': 3, 'min_samples_leaf': 0.30000000000000004, 'max_samples': 0.2, 'max_features': 0.2}
{'n_estimators': 3, 'min_samples_leaf': 0.30000000000000004, 'max_samples': 0.2, 'max_features': 0.2}


AttributeError: 'RandomForestRegressor' object has no attribute 'best_score_'